### PR TITLE
designed for desktop

### PR DESCRIPTION
**Pull request by MasanoriEnoki**
ヘッダーを修正し、ダミー文章を作りました。

---
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/enoki-site/6)

### CODE REVIEW

**Review by hrl7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/enoki-site/6)* status: all files reviewed, 2 unresolved discussions (waiting on @MasanoriEnoki)

___
*[index.html, line 28 at r1](https://reviewable.io/reviews/tigerscave/enoki-site/6#-M5WCqf_5rwKZtVpsGhX:-M5WCqf_5rwKZtVpsGhY:bpbvrhq) ([raw file](https://github.com/tigerscave/enoki-site/blob/6b6475c3a139636a42be5ae320450907e6447cf0/index.html#L28)):*
> ```HTML
>         <ul class="content">
>           <li>
>             <div class="btninfo">
> ```

btnとinfoの間にハイフンとかいれると読みやすそう
"btn-info" みたいに
___
*[index.html, line 53 at r1](https://reviewable.io/reviews/tigerscave/enoki-site/6#-M5WD-oW8-N2ygihPKw_:-M5WD-oW8-N2ygihPKwa:bldxcm6) ([raw file](https://github.com/tigerscave/enoki-site/blob/6b6475c3a139636a42be5ae320450907e6447cf0/index.html#L53)):*
https://developer.mozilla.org/ja/docs/Web/HTML/Element/main
> 文書には hidden 属性が指定されていない <main> 要素を2つ以上置くことはできません。

**Review by azamiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/enoki-site/6)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @hrl7 and @MasanoriEnoki)

___
*[index.html, line 25 at r2](https://reviewable.io/reviews/tigerscave/enoki-site/6#-M5WSayy9H5pChlZGBYZ:-M5WSayy9H5pChlZGBY_:bfub5gd) ([raw file](https://github.com/tigerscave/enoki-site/blob/db5a39d2ca0730f0807f6ee3df9c53712a10c8a4/index.html#L25)):*
> ```HTML
>         </div>
>       </div>
>       <div class="contentsbar">
> ```

`contens-bar`

**Review by MasanoriEnoki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/enoki-site/6)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @azamiya and @hrl7)

___
*[index.html, line 28 at r1](https://reviewable.io/reviews/tigerscave/enoki-site/6#-M5WCqf_5rwKZtVpsGhX:-M5_bBm49a4PRTtuFuaa:b-896fix) ([raw file](https://github.com/tigerscave/enoki-site/blob/6b6475c3a139636a42be5ae320450907e6447cf0/index.html#L28)):*
<details><summary><i>Previously, hrl7 (zigen) wrote…</i></summary><blockquote>

btnとinfoの間にハイフンとかいれると読みやすそう
"btn-info" みたいに
</blockquote></details>

Done.
___
*[index.html, line 53 at r1](https://reviewable.io/reviews/tigerscave/enoki-site/6#-M5WD-oW8-N2ygihPKw_:-M5_dHWHDxBsDdhoEiNN:b-896fix) ([raw file](https://github.com/tigerscave/enoki-site/blob/6b6475c3a139636a42be5ae320450907e6447cf0/index.html#L53)):*
<details><summary><i>Previously, hrl7 (zigen) wrote…</i></summary><blockquote>

https://developer.mozilla.org/ja/docs/Web/HTML/Element/main
> 文書には hidden 属性が指定されていない <main> 要素を2つ以上置くことはできません。


</blockquote></details>

Done.
___
*[index.html, line 25 at r2](https://reviewable.io/reviews/tigerscave/enoki-site/6#-M5WSayy9H5pChlZGBYZ:-M5_dDu853Vq_8OvwWQF:b-896fix) ([raw file](https://github.com/tigerscave/enoki-site/blob/db5a39d2ca0730f0807f6ee3df9c53712a10c8a4/index.html#L25)):*
<details><summary><i>Previously, azamiya wrote…</i></summary><blockquote>

`contens-bar`
</blockquote></details>

Done.

**Review by azamiya — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/enoki-site/6)* status: all files reviewed, 2 unresolved discussions (waiting on @hrl7)

**Review by azamiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/enoki-site/6)* status: all files reviewed, 2 unresolved discussions (waiting on @hrl7)

**Pull request merged**
